name: "Kim Leabres"
description: "Trying hard"

url: "https://kbleabres.github.io"
github: kbleabres

paginate: 3

markdown: rdiscount
permalink: pretty
pygments: true

exclude: [Rakefile]
theme: jekyll-theme-minimal